/**
 * User capability definitions — stable public API.
 * Code should always check capabilities, never role names directly.
 */

export const USER_CAPABILITIES = [
  "content:read",
  "content:create",
  "content:update",
  "content:delete",
  "content:publish",
  "content:revisions:read",
  "content:revisions:restore",
  "content:revisions:discard",
  "media:read",
  "media:upload",
  "media:delete",
  "comments:moderate",
  "users:read",
  "users:manage",
  "plugins:read",
  "plugins:install",
  "plugins:activate",
  "plugins:delete",
  "themes:read",
  "themes:install",
  "themes:activate",
  "themes:delete",
  "settings:read",
  "settings:manage",
  "updates:manage",
  "site:admin",
  "shop:settings",
  "products:read",
  "products:create",
  "products:update",
  "products:delete",
  "products:publish",
  "inventory:read",
  "inventory:adjust",
  "orders:read",
  "orders:create",
  "orders:update",
  "payments:read",
  "payments:capture",
  "payments:refund",
  "fulfillments:read",
  "fulfillments:manage",
  "returns:read",
  "returns:manage",
  "customers:read",
  "customers:manage",
  "discounts:read",
  "discounts:manage",
  "tax:read",
  "tax:manage",
  "shop:reports",
] as const;

export type UserCapability = (typeof USER_CAPABILITIES)[number];

export const ROLE_CAPABILITIES: Record<string, UserCapability[]> = {
  administrator: [...USER_CAPABILITIES],
  editor: [
    "content:read",
    "content:create",
    "content:update",
    "content:delete",
    "content:publish",
    "content:revisions:read",
    "content:revisions:restore",
    "content:revisions:discard",
    "media:read",
    "media:upload",
    "media:delete",
    "comments:moderate",
    "users:read",
    "products:read",
    "products:create",
    "products:update",
    "products:publish",
    "inventory:read",
    "orders:read",
    "orders:update",
    "payments:read",
    "customers:read",
    "discounts:read",
    "tax:read",
    "shop:reports",
  ],
  author: [
    "content:read",
    "content:create",
    "content:update",
    "content:revisions:read",
    "content:revisions:restore",
    "content:revisions:discard",
    "media:read",
    "media:upload",
  ],
  contributor: ["content:read", "content:create", "content:revisions:read"],
  subscriber: ["content:read"],
};

export function roleHasCapability(role: string, capability: UserCapability): boolean {
  return ROLE_CAPABILITIES[role]?.includes(capability) ?? false;
}
