// SPDX-License-Identifier: MIT

import { isAccountPath } from "../../middleware/account-cache.js";
import type { PwaSettings } from "./pwa-settings.js";

export const PWA_OFFLINE_URL = "/pwa-offline.html";

function cacheName(cacheVersion: number): string {
  return `jf-pwa-v${cacheVersion}`;
}

/**
 * Build the active service worker script.
 *
 * Deliberately dependency-free (no Workbox) so the whole worker ships as one
 * small, readable file with no bundling step — consistent with "no source
 * checkout or build tooling required" elsewhere in this project.
 *
 * Strategy, matching the issue's cache-safety requirements:
 * - Navigations are network-only; a failed navigation falls back to the
 *   precached offline page. Nothing HTML is ever written to a cache.
 * - Only an explicit static-asset allowlist (`/uploads/`, `/theme.css`,
 *   `/assets/`, `/css-providers/`, `/public/`) is cache-eligible, and only
 *   when `assetCache.enabled` — stale-while-revalidate, bounded by
 *   `maxEntries` (oldest-insertion eviction) and `maxAgeSeconds` (checked
 *   against the cached response's own `Date` header).
 * - Everything else — `/admin`, `/api`, `/login`, `/install`, non-GET,
 *   cross-origin, and any request carrying an `Authorization` header — is
 *   never intercepted at all; the browser handles it exactly as it would
 *   with no service worker installed.
 */
export function buildServiceWorkerScript(settings: PwaSettings, privatePaths: readonly { path: string; match: "exact" | "prefix" }[] = []): string {
  const CACHE = cacheName(settings.cacheVersion);
  const precache: string[] = [PWA_OFFLINE_URL];
  if (settings.offline.imageUrl && !isAccountPath(settings.offline.imageUrl) && !privatePaths.some(rule => settings.offline.imageUrl === rule.path || (rule.match === "prefix" && settings.offline.imageUrl.startsWith(`${rule.path}/`)))) precache.push(settings.offline.imageUrl);

  const assetCacheEnabled = settings.assetCache.enabled;
  const maxEntries = settings.assetCache.maxEntries;
  const maxAgeSeconds = settings.assetCache.maxAgeSeconds;

  return `// Generated by Justflows — Settings → PWA. Do not edit; regenerate by saving settings.
const CACHE = ${JSON.stringify(CACHE)};
const CACHE_PREFIX = "jf-pwa-";
const PRECACHE_URLS = ${JSON.stringify(precache)};
const OFFLINE_URL = ${JSON.stringify(PWA_OFFLINE_URL)};
const ASSET_CACHE_ENABLED = ${JSON.stringify(assetCacheEnabled)};
const ASSET_MAX_ENTRIES = ${JSON.stringify(maxEntries)};
const ASSET_MAX_AGE_SECONDS = ${JSON.stringify(maxAgeSeconds)};
const ASSET_ALLOWLIST = [/^\\/uploads\\//, /^\\/theme\\.css$/, /^\\/assets\\//, /^\\/css-providers\\//, /^\\/public\\//];
const PRIVATE_PATHS = ${JSON.stringify(privatePaths)};
const NAV_BYPASS = /^\\/(admin|api|login|install|account|platform-account|ext)(\\/|$)/;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .catch(() => {
        // Storage unavailable or quota exceeded: the worker still installs,
        // it just has nothing precached — online browsing is unaffected.
      }),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE)
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

function isAssetCacheable(pathname) {
  return ASSET_ALLOWLIST.some((re) => re.test(pathname));
}

function isExpired(response, maxAgeSeconds) {
  const dateHeader = response.headers.get("date");
  if (!dateHeader) return false;
  const ageSeconds = (Date.now() - new Date(dateHeader).getTime()) / 1000;
  return ageSeconds > maxAgeSeconds;
}

async function trimCache(cache, maxEntries) {
  try {
    const keys = await cache.keys();
    if (keys.length > maxEntries) await cache.delete(keys[0]);
  } catch {
    // best-effort only
  }
}

function isCacheableResponse(response) {
  return (
    response &&
    response.status === 200 &&
    !response.redirected &&
    response.type === "basic" &&
    !(response.headers.get("cache-control") || "").includes("no-store") &&
    !(response.headers.get("cache-control") || "").includes("private")
  );
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request);

  const network = fetch(request)
    .then(async (response) => {
      if (isCacheableResponse(response)) {
        try {
          await cache.put(request, response.clone());
          await trimCache(cache, ASSET_MAX_ENTRIES);
        } catch {
          // quota exceeded or storage unavailable: serve the network response anyway
        }
      }
      return response;
    })
    .catch(() => null);

  if (cached && !isExpired(cached, ASSET_MAX_AGE_SECONDS)) {
    event_waitUntilSafe(network);
    return cached;
  }
  const fresh = await network;
  return fresh || cached || Response.error();
}

// Fire-and-forget the background revalidation without unhandled-rejection noise.
function event_waitUntilSafe(promise) {
  promise.catch(() => {});
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  if (request.headers.has("authorization")) return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    if (NAV_BYPASS.test(url.pathname) || PRIVATE_PATHS.some(rule => url.pathname.replace(/\\/$/, "") === rule.path || (rule.match === "prefix" && url.pathname.startsWith(rule.path + "/")))) return;
    event.respondWith(
      fetch(request).catch(() => caches.match(OFFLINE_URL).then((r) => r || Response.error())),
    );
    return;
  }

  if (ASSET_CACHE_ENABLED && isAssetCacheable(url.pathname)) {
    event.respondWith(staleWhileRevalidate(request));
  }
});
`;
}

/**
 * Served at the same `/sw.js` URL once PWA is disabled, so an already
 * installed client can still reach a worker there. It removes every
 * PWA cache and unregisters itself, then asks open tabs to reload once so
 * they stop being controlled by a stale worker.
 */
export function buildRetirementServiceWorkerScript(): string {
  return `// Generated by Justflows — PWA disabled. Retires the previously installed worker.
const CACHE_PREFIX = "jf-pwa-";

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX)).map((name) => caches.delete(name))),
      )
      .then(() => self.registration.unregister())
      .then(() => self.clients.matchAll())
      .then((clients) => clients.forEach((client) => client.navigate(client.url))),
  );
});
`;
}
